version: "3.3"
services:
  backend:
    image: node:16-alpine
    working_dir: /usr/src/app
    command: sh -c "npm install && npm run start:dev"
    volumes:
      - ./backend:/usr/src/app
    expose:
      - 3000
    depends_on:
      - postgres

  kanban:
    image: node:16-alpine
    working_dir: /usr/src/app
    command: sh -c "npm install && npm run watch"
    volumes:
      - ./kanban:/usr/src/app
    expose:
      - 4200

  frontend:
    image: node:16-alpine
    working_dir: /usr/src/app
    command: sh -c "npm install && npm run start"
    volumes:
      - ./frontend:/usr/src/app
    expose:
      - 4200

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: kanban
      POSTGRES_PASSWORD: password
      POSTGRES_DB: kanban
    # command: postgres -c max_locks_per_transaction=1000
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - ./docker/postgres:/docker-entrypoint-initdb.d

  nginx:
    volumes:
      - ./docker/nginx/dev.conf:/etc/nginx/conf.d/app.conf
      - ./landing:/var/www/landing
      - ./kanban:/var/www/kanban
    image: nginx
    ports:
      - 80:80
    depends_on:
      - frontend
      - backend
      - kanban
